### ISSUE TITLE
Valid CPFs being declined

### ISSUE THREAD

**Issue by willianocarvalho** [leonardocaldas/flutter-cpf-cnpj-validator#4]
012.849.332-10
036.068.160-30

**Comment by isorensen** [comment]
@willianocarvalho , I ran a unit test and both these cpf numbers returned valid:  

![image](https://user-images.githubusercontent.com/3399976/90021508-c01c5780-dc87-11ea-91ff-0321bedc723e.png)  

Maybe you should put here your usage example, since there might be an error in your code.

**Comment by gussouzauni** [comment]
thanks for contributing @isorensen

**Comment by leonardocaldas** [comment]
@willianocarvalho I'll be closing this issue since it was already confirmed that the lib is giving the correct results.
